coverage:
  precision: 2
  round: down
  range: "60...100"

  status:
    project:
      default:
        target: 85%
        threshold: 2%
        informational: false
    patch:
      default:
        target: 80%
        threshold: 5%
        informational: true

comment:
  layout: "reach,diff,flags,files"
  behavior: default
  require_changes: true
  require_base: false
  require_head: true

ignore:
  - "**/*_test.go"
  - "**/testdata/**"
  - "**/testutil/**"
  - "cmd/**"

flags:
  unittests:
    paths:
      - pkg/
    carryforward: true
